#%RAML 1.0 ResourceType
  
  get?:
    description: GET <<resourcePath>>
    
    # Use imported 'traits'
    is:
      - traitsTypesLib.hasAcceptHeader
      - traitsTypesLib.hasError: {errorCode: 404}
    
    responses:
      200:
        # Response Headers
        headers:
          Content-Type:
            
        body:
          dataTypesLib.<<resourcePathName| !uppercamelcase | !singularize>>[]

  post:
    description: POST <<resourcePath>>

    # Use imported 'traits'
    is:
      - traitsTypesLib.hasAcceptHeader
      - traitsTypesLib.hasError: {errorCode: 500}

    body:
      dataTypesLib.<<resourcePathName| !uppercamelcase| !singularize>>
    
    responses:
      201:
        # Response Headers
        headers:
          Location:      
        body:
      