#%RAML 1.0 NamedExample
value:
  bookingId: b2
  bookingStartDate: 2022-09-10
  bookingEndDate: 2022-09-15
  # Way to specify array in examples
  amenitiesSelected: 
    - wifi
    - dry cleaning
    - gym
  transportSelected:
    - vallet service
    - limousine service
  food: vegetarian    
  room:
    roomId: rm1
    roomType: single room
    amount: 40000
